# Generated by Django 5.2.16 on 2026-07-21 07:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True, help_text="URL-friendly identifier")),
                ("address", models.TextField()),
                ("location", django.contrib.gis.db.models.fields.PointField(geography=True, help_text="Geographic coordinates (longitude, latitude) — PostGIS GEOGRAPHY point", srid=4326)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("license_number", models.CharField(blank=True, help_text="DGDA pharmacy license number", max_length=100)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("is_open_on_sunday", models.BooleanField(default=True)),
                ("is_open_on_saturday", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True, help_text="Is this pharmacy visible and accepting discovery requests?")),
                ("is_verified", models.BooleanField(default=False, help_text="Has the pharmacy's license been verified by platform admin?")),
                ("photo", models.ImageField(blank=True, upload_to="pharmacy_photos/")),
                ("owner", models.ForeignKey(help_text="User who manages this pharmacy storefront", on_delete=django.db.models.deletion.CASCADE, related_name="pharmacies", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Pharmacy",
                "verbose_name_plural": "Pharmacies",
                "db_table": "pharmacies_pharmacy",
                "indexes": [
                    models.Index(fields=["is_active", "is_verified"], name="pharm_active_verified_idx"),
                ],
            },
        ),
    ]
