# Generated by Django 5.2.16 on 2026-07-21 07:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterMedicine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generic_name", models.CharField(db_index=True, help_text="Generic / INN name (e.g., Paracetamol)", max_length=300)),
                ("brand_name", models.CharField(blank=True, help_text="Brand/trade name if different from generic", max_length=300)),
                ("dosage_form", models.CharField(blank=True, help_text="e.g., Tablet, Syrup, Injection, Cream", max_length=100)),
                ("strength", models.CharField(blank=True, help_text="e.g., 500mg, 250mg/5ml", max_length=100)),
                ("manufacturer", models.CharField(blank=True, help_text="Manufacturer company name", max_length=300)),
                ("is_active", models.BooleanField(default=True, help_text="Is this entry available for pharmacy listings?")),
            ],
            options={
                "verbose_name": "Master Medicine",
                "verbose_name_plural": "Master Medicines",
                "db_table": "catalog_master_medicine",
                "indexes": [
                    models.Index(fields=["generic_name", "brand_name"], name="catalog_master_generic_brand_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PharmacyMedicineListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fallback_generic_name", models.CharField(blank=True, max_length=300)),
                ("fallback_brand_name", models.CharField(blank=True, max_length=300)),
                ("fallback_dosage_form", models.CharField(blank=True, max_length=100)),
                ("fallback_strength", models.CharField(blank=True, max_length=100)),
                ("fallback_manufacturer", models.CharField(blank=True, max_length=300)),
                ("price", models.DecimalField(decimal_places=2, help_text="Current selling price in BDT", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ("is_available", models.BooleanField(default=True, help_text="Is this medicine currently in stock?")),
                ("notes", models.TextField(blank=True, help_text="Optional pharmacy-specific notes (e.g., 'generic available')")),
                ("master_medicine", models.ForeignKey(blank=True, help_text="Canonical medicine entry (NULL until admin normalizes free-text entries)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pharmacy_listings", to="catalog.mastermedicine")),
                ("pharmacy", models.ForeignKey(help_text="The pharmacy offering this medicine", on_delete=django.db.models.deletion.CASCADE, related_name="medicine_listings", to="pharmacies.pharmacy")),
            ],
            options={
                "verbose_name": "Pharmacy Medicine Listing",
                "verbose_name_plural": "Pharmacy Medicine Listings",
                "db_table": "catalog_pharmacy_medicine_listing",
                "constraints": [
                    models.UniqueConstraint(
                        fields=["pharmacy", "master_medicine"],
                        name="uq_pharmacy_master_medicine",
                        condition=models.Q(("master_medicine__isnull", False)),
                        violation_error_message="This pharmacy already lists this master medicine.",
                    ),
                ],
                "indexes": [
                    models.Index(fields=["pharmacy", "is_available"], name="catalog_pharm_pharm_is_avail_idx"),
                    models.Index(fields=["master_medicine", "is_available"], name="catalog_pharm_master_avail_idx"),
                    models.Index(
                        fields=["pharmacy"],
                        name="idx_unlisted_listings",
                        condition=models.Q(("master_medicine__isnull", True)),
                    ),
                ],
            },
        ),
    ]
