# Generated by Django 5.2.16 on 2026-07-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotifySubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_phone", models.CharField(db_index=True, help_text="Phone number to send notification to", max_length=15)),
                ("latitude", models.FloatField(help_text="Customer's reference latitude for proximity check")),
                ("longitude", models.FloatField(help_text="Customer's reference longitude for proximity check")),
                ("radius_km", models.PositiveIntegerField(default=5, help_text="Search radius in kilometers")),
                ("is_active", models.BooleanField(default=True, help_text="Is this subscription active?")),
                ("master_medicine", models.ForeignKey(help_text="The medicine the customer wants to be notified about", on_delete=django.db.models.deletion.CASCADE, related_name="notify_subscriptions", to="catalog.mastermedicine")),
            ],
            options={
                "verbose_name": "Notify Subscription",
                "verbose_name_plural": "Notify Subscriptions",
                "db_table": "notifications_notify_subscription",
                "indexes": [
                    models.Index(fields=["customer_phone", "master_medicine"], name="notify_customer_med_idx"),
                ],
            },
        ),
    ]
